---
- hosts: local
  tasks:
   - name: Install docker
     apt: name={{item}} state=installed update_cache=true
     with_items:
       - docker.io
       - cifs-utils
       - flashplugin-installer
       - fish
