---
- hosts: local
  tasks:
   - name: Install docker
     apt: name={{item}} state=installed update_cache=true
     with_items:
       - docker.io
       - cifs-utils
       - flashplugin-installer
       - fish
   - group: name=docker state=present
   - service: name=docker state=restarted
   - user: name={{item}} groups=docker append=yes
     with_items:
       - m999jve
